In [75]:
d2_path = "KhoHo/sparse_d_1_2_5"
d1_path = "KhoHo/sparse_d_1_3_5"

In [45]:
import numpy as np

In [65]:
def file_to_differential(path):
    s = ""
    with open(path, 'r') as reader:
        s = reader.read()[10:-3]
    
    rows = []
    cols = []
    vals = []
    
    bitmask = np.int64(2**32)
    
    for elem in s.split(", "):
        n = np.int64(elem)
        rows.append((abs(n) // bitmask) - 1)
        cols.append((abs(n) % bitmask) - 1)
        vals.append(1 if n > 0 else -1)
    
    return vals, (rows, cols)

# file_to_differential(path)

In [77]:
import scipy
import scipy.sparse
import scipy.sparse.linalg

# generate differential matrices
d1 = scipy.sparse.coo_matrix(file_to_differential(d1_path)).asfptype()
d2 = scipy.sparse.coo_matrix(file_to_differential(d2_path)).asfptype()

# d1 = scipy.sparse.coo_matrix([[6,4,5],[6,3,1],[6,3,7]]).asfptype()
# d2 = scipy.sparse.coo_matrix([[6,4,5],[6,3,1],[6,3,7]]).asfptype()

# compute laplacian from differentials
laplacian = (d2 * d2.transpose())+(d1.transpose() * d1)

# print(laplacian.toarray())

# get smallest eigenpair
eig_val, eig_vec = scipy.sparse.linalg.eigsh(laplacian, k=1, sigma=0, maxiter=1000)
print(eig_val)

[2.58578644]


In [67]:
print(d1.toarray())

[[ 1. -1.  1. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  0. -1.]
 [ 0.  0.  0. ...  0.  0. -1.]
 [ 0.  0.  0. ...  0.  0. -1.]]


In [68]:
print(d2.toarray())

[[ 1. -1.  1. ...  0.  0.  0.]
 [ 1.  0.  0. ...  0.  0.  0.]
 [ 0.  1.  0. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  1.  0.]
 [ 0.  0.  0. ...  0.  1.  0.]
 [ 0.  0.  0. ...  0.  0.  1.]]
